# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- if .Values.nifiRegistry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-reg-cm
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiRegistry) | nindent 4 -}}
    app: {{ .Values.name }}-reg
data:
  NIFI_REGISTRY_WEB_HTTP_PORT: "18080"
  NIFI_REGISTRY_BUCKET_COUNT: "{{ .Values.nifiRegistry.buckets | len }}"
{{- range $i,$bucket := .Values.nifiRegistry.buckets }}
  NIFI_REGISTRY_BUCKET_FILES_{{ $i }}: {{ join "," $bucket.flowfiles | quote }}
  NIFI_REGISTRY_BUCKET_NAME_{{ $i }}: {{ $bucket.name | quote }}
{{- end -}}
{{- end -}}

