# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- if .Values.nifiRegistry.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-reg
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiRegistry) | nindent 4 -}}
    name: {{ .Values.name }}-reg
    app: {{ .Values.name }}-reg
  annotations:
    app.kubernetes.io/name: {{ .Values.name }}-reg
    app.kubernetes.io/part-of: {{ .Values.name }}
spec:
  revisionHistoryLimit: 1
  serviceName: {{ .Values.name }}-reg
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: {{ .Values.name }}-reg
  template:
    metadata:
      labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiRegistry) | nindent 8 -}}
        app: {{ .Values.name }}-reg
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
{{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}
      imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
{{- end }}
      initContainers:
      - name: ensure-conf
        image: {{ .Values.nifiRegistry.image }}
        imagePullPolicy: {{ .Values.nifiRegistry.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-reg-cm
            optional: false
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
          readOnlyRootFilesystem: true
        {{- end }}
        {{- if .Values.nifiRegistry.resources }}
        resources: {{ toYaml .Values.nifiRegistry.resources | nindent 10 }}
        {{- end }}
        command:
        - sh
        - "-c"
        - |
          if [ -z "$(ls -A -- /mnt/store/nifi-registry/conf)" ]; then
            echo Copying files into conf directory
            cp -r /opt/nifi-registry/nifi-registry-current/conf/ /mnt/store/nifi-registry/
          fi

        volumeMounts:
        - name: statedata
          mountPath: /mnt/store/nifi-registry/conf
          subPath: conf
          readOnly: false
      containers:
      - name: nifi-registry
        image: {{ .Values.nifiRegistry.image }}
        imagePullPolicy: {{ .Values.nifiRegistry.imagePullPolicy }}
        ports:
        - containerPort: 18080
          name: http
        - containerPort: 18443
          name: https
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-reg-cm
              optional: false
{{- include "idol-library.util.range_array_or_map_values" (dict "root" . "vals" .Values.nifiRegistry.envFrom) | nindent 10 }}
        livenessProbe:
          exec:
            command:
              #Registry image doesn't have pgrep or ps
              - sh
              - -c
              - ls -l /proc/*/exe | grep java
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        {{- if .Values.nifiRegistry.resources }}
        resources: {{ toYaml .Values.nifiRegistry.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: /data
            name: data
            subPath: data
          - name: scripts
            mountPath: /scripts
            readOnly: false
          - name: statedata
            mountPath: /opt/nifi-registry/nifi-registry-current/conf
            subPath: conf
            readOnly: false
          - name: statedata
            mountPath: /opt/nifi-registry/nifi-registry-current/database
            subPath: database
            readOnly: false
          - name: statedata
            mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
            subPath: flow_storage
            readOnly: false
          - name: statedata
            mountPath: /opt/nifi-registry/nifi-registry-current/run
            subPath: run
            readOnly: false
          {{- range .Values.additionalVolumeMounts }}
          - {{ toYaml . | indent 12 | trim }}
          {{- end }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - /scripts/postStart.sh
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 2Gi
        - name: scripts
          configMap:
            name: {{ .Values.name }}-reg-scripts-cm
            optional: false
            defaultMode: 0755
        {{- range .Values.additionalVolumes }}
        - {{ toYaml . | indent 10 | trim }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: statedata
      labels: {{- include "idol-library.labels.volumeClaimTemplates" (dict "root" . "component" .Values.nifiRegistry) | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.nifiRegistry.dataVolume.storageClass }}
      resources:
        requests:
          storage: {{ .Values.nifiRegistry.dataVolume.volumeSize }}
{{- end -}}
