# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-idol-config
  labels: {{- include "idolfind.labels" . | nindent 4 }}
data:
  community.cfg: |
{{ tpl (.Files.Get "resources/community.cfg") . | indent 4 }}

  find_config.json: |
{{ tpl (.Files.Get "resources/find_config.json") . | indent 4 }}

  view.cfg: |
{{ tpl (.Files.Get "resources/view.cfg") . | indent 4 }}
