# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.viewServerName }}
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values) | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.viewServerACIPort | int }}
    targetPort: {{ .Values.idolACIPortName }}
    name: {{ .Values.idolACIPortName }}
  selector:
    app: {{ .Values.viewServerName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.viewServerName }}
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.viewServerName }}
  template:
    metadata:
      labels: {{- include "idol-library.labels" (dict "root" . "component" .Values) | nindent 8 }}
        app: {{ .Values.viewServerName }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ .Values.viewServerName }}
        image: {{ .Values.idolImageRegistry }}/{{ .Values.viewServerImage }}:{{ .Values.idolVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbePath }}
            port: {{ .Values.viewServerACIPort | int }}
{{- template "idol-library.standardLivenessProbe" .Values.viewServerLivenessProbe }}
        ports:
        - containerPort: {{ .Values.viewServerACIPort | int }}
          name: {{ .Values.idolACIPortName }}
          protocol: TCP
        volumeMounts:
        - name: config-map
          mountPath: /etc/config/idol
        - name: viewing-dir
          mountPath: /idol-ingest
        env:
        - name: IDOL_COMPONENT_CFG
          value: "/etc/config/idol/view.cfg"
      volumes:
      - name: config-map
        configMap:
          name: {{ .Release.Name }}-idol-config
      - name: viewing-dir
        emptyDir: {}
