# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022-2023 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: v2
name: single-content
version: 0.5.0
appVersion: "24.1"
description: A configurable single-IDOL setup
dependencies:
- name: idol-library
  version: "0.5.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: "0.1.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
