# BEGIN COPYRIGHT NOTICE
# Copyright 2022-2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

# As per https://helm.sh/docs/topics/charts/#the-chart-file-structure
# this values.yaml file contains the default configuration values for this distributed-idol chart.
# These default values can be overridden by using the --values or --set flags on the `helm install`
# command: see https://helm.sh/docs/helm/helm_install/

##### HIGH LEVEL CHART CONFIGURATION #####
# This section contains parameters that are most likely to be overridden for
# the basic choices and constraints around how this chart will be used.

global:
  # -- Global override value for idolImage.registry
  idolImageRegistry: ""
  # -- Global override value for idolImage.version
  idolVersion: ""
  # -- Global secrets used to pull container images
  imagePullSecrets:
  - "dockerhub-secret"

idolImage:
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  registry: "microfocusidolserver"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  version: "24.1"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}.
  repo: "content"


# contentVolumeSize -- Size of the PersistentVolumeClaim that is created
# for each Content instance. The Kubernetes cluster will need to provide
# enough PersistentVolumes to satisify the claims made for the desired number
# of Content instances. The size chosen here provides a hard limit on the size
# of the Content index in each Content instance.
contentVolumeSize: 16Gi

# contentStorageClass -- Name of the storage class used to provision a PersistentVolume
# for each Content instance.
# The associated PVCs are named index-{name}-{pod number}
contentStorageClass: "idol-content-storage-class"
#############################################

# -- port service will serve ACI connections on
aciPort: "9100"
# -- port service will serve service connections on
servicePort: "9102"
# -- port service will serve index connections on
indexPort: "9101"

# -- whether aci/service/index ports are configured to use TLS (https).
# If configuring for TLS, then consider setting IDOL_SSL_COMPONENT_CERT_PATH and IDOL_SSL_COMPONENT_KEY_PATH in envConfigMap
# to provide required TLS certificates
usingTLS: false

# existingConfigMap -- if specified, mounted at /etc/config/idol and expected to provide $IDOL_COMPONENT.cfg
#                      or content.cfg if $IDOL_COMPONENT is unavailable.
existingConfigMap: ""

# -- Additional PodSpec Volume (see https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes)
additionalVolumes: []

# -- Additional PodSpec VolumeMount (see https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1)
additionalVolumeMounts: []

# -- Optional configMap name holding extra environnment variables for content container
envConfigMap: ""

# -- Optional PodSecurityContext (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podsecuritycontext-v1-core)
podSecurityContext:
  # -- enable PodSecurityContext. Setting to false omits.
  enabled: false
  fsGroup: 0
  runAsUser: 1000
  runAsGroup: 0

# -- Optional SecurityContext for container (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#securitycontext-v1-core)
containerSecurityContext:
  # -- enable SecurityContext for container. Setting to false omits.
  enabled: false
  
##### NETWORKING CONFIGURATION #####
# This section contains parameters to configure various network-related
# properties in this chart.

ingress:
  # -- Create ingress resource
  enabled: true

  # -- Ingress controller type to setup for.
  # Valid values are nginx or haproxy (used by OpenShift)
  type: nginx

  # -- Optional parameter to override the default ingress class
  className: ""

  # -- Optional host (see https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules).
  # For an OpenShift environment this is required (see https://docs.openshift.com/container-platform/4.11/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)
  host: ""

  # -- Ingress controller path for ACI connections.
  path: "/content/"

  # -- Ingress controller path for index connections.
  indexPath: "/index/"

  # -- Maximum allowed size of the client request body, defining
  # the maximum size of requests that can be made to IDOL components within the installation, e.g.
  # the amount of data sent in DREADDDATA index commands.
  # The value should be an nginx "size" value.
  # See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size for the documentation of the
  # corresponding nginx configuration parameter.
  proxyBodySize: 2048m
  
  # -- Ingress controller specific annotations
  # Some annotations are added automatically based on ingress.type and other values, but can 
  # be overriden/augmented here
  # e.g. https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations
  annotations: {}

#####################################


##### INTERNAL VARIABLES #####
# Values specified below this point in the file should not need to be overriden.
# They are generally here in values.yaml so that DRY principles and a consistent
# scheme for specifying these values in the templates can be followed.

# licenseServerHostname -- maps to [License] LicenseServerHost in the IDOL cfg files
# Should point to a resolvable IDOL LicenseServer (or Kubernetes service abstraction - see the idol-licenseserver chart)
licenseServerHostname: "idol-licenseserver"
# licenseServerPort -- the ACI port of the IDOL LicenseServer (or abstraction)
licenseServerPort: "20000"

# queryserviceName -- internal parameter to specify the query service name, if this is empty then no
#                     additional service will be provisioned.
queryserviceName: "idol-query-service"
# queryserviceACIPort -- port idol-query-service will serve ACI connections on.
queryserviceACIPort: "9060"
# indexserviceName -- internal parameter to specify the index service name, if this is empty then no
#                     additional service will be provisioned.
indexserviceName: "idol-index-service"
# indexserviceACIPort -- the port idol-index-service will serve ACI connections on.
indexserviceACIPort: "9070"

# name -- used to name statefulset, service, ingress
name: "idol-content"

# subchart values
idol-licenseserver:
# create a cluster service proxying to a LicenseServer instance
  # -- whether to deploy the idol-licenseserver sub-chart
  enabled: true
  # @ignore required subchart value
  licenseServerIp: this must be set to a valid IP address