# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:

    scrape_configs:
      - job_name: dih
        static_configs:
        - targets: [ '{{ .Values.dih.name }}:9118' ]