# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE

{{ include "idol-library.ingress" (dict 
    "root" .
    "component" .Values.prometheus
    "ingress" .Values.prometheus.ingress
    "destination" "distributedidol.prometheus.ingress")  -}}
{{- define "distributedidol.prometheus.ingress" -}}
{{/* Any prometheus specific merges to base template go here */}}
{{- end -}}
