# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
{{- if and (.Values.autoscaling.enabled) (not .Values.setupMirrored) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.prometheus.port | int }}
    targetPort: prometheus-port
    name: prometheus-port
  selector:
    app: {{ .Values.prometheus.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels: {{- include "distributedidol.labels" . | nindent 8 }}
        app: {{ .Values.prometheus.name }}
    spec:
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ .Values.prometheus.name }}
        image: prom/prometheus:v2.14.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
        ports:
        - containerPort: {{ .Values.prometheus.port | int }}
          name: prometheus-port
          protocol: TCP
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.external-url=/prometheus'
        - '--web.route-prefix=/'
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          emptyDir: {}
{{- end }}