# BEGIN COPYRIGHT NOTICE
# Copyright 2022-2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.licenseServerService }}
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values) | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.licenseServerPort | int }}
      targetPort: {{ .Values.licenseServerPort | int }}
      name: aci-port
  {{- if .Values.licenseServerExternalName }}
  type: ExternalName
  externalName: {{ .Values.licenseServerExternalName | quote }}
  {{- else }}
  # no selector, create endpoint manually
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.licenseServerService }}
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values) | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.licenseServerIp | quote }}
    ports:
      - port: {{ .Values.licenseServerPort | int }}
        name: aci-port
  {{- end }}