# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels: {{- include "singlecontent.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.name | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: {{- include "singlecontent.labels" . | nindent 8 }}
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
          {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      terminationGracePeriodSeconds: 300
      containers:
      - name: {{ .Values.name }}
        image: {{ print (default .Values.idolImage.registry (dig "global" "idolImageRegistry" "" (.Values | merge dict )))
                      "/"  .Values.idolImage.repo  ":" 
                      (default .Values.idolImage.version (dig "global" "idolVersion" "" (.Values | merge dict ))) }}
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        args: 
        - "-c"
        - |
{{ tpl (.Files.Get "resources/content_startup.sh") . | indent 10 }}
        volumeMounts:
        - name: config-map
          mountPath: /etc/config/idol
        - name: index
          mountPath: /opt/idol/content/index
        {{- range .Values.additionalVolumeMounts }}
        - {{ . | toYaml | nindent 10 }}
        {{- end }}
        env:
        - name: IDOL_CONTENT_SERVICE_PORT_ACI_PORT
          # This doesn't seem to be set by our headless service
          value: {{ .Values.aciPort | quote }}
        - name: IDOL_COMMAND_PARAMS
          value: "-idolcluster"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - "-c"
              - |
{{ tpl (.Files.Get "resources/content_postStart.sh") . | indent 16 }}
        livenessProbe:
          httpGet:
            path: /a=getpid
            port: {{ .Values.aciPort | int }}
{{- template "idol-library.standardLivenessProbe" .Values.livenessProbe }}
        ports:
        - containerPort: {{ .Values.aciPort | int }}
          name: aci-port
          protocol: TCP
        - containerPort: {{ .Values.servicePort | int }}
          name: service-port
          protocol: TCP
        - containerPort: {{ .Values.indexPort | int }}
          name: index-port
          protocol: TCP
      volumes:
      - name: config-map
        configMap:
          name: {{ default (printf "%s-default-cfg" .Values.name) .Values.existingConfigMap }}
      {{- range .Values.additionalVolumes }}
      - {{ . | toYaml | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: index
      labels: {{- include "singlecontent.labels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.contentStorageClass }}
      resources:
        requests:
          storage: {{ .Values.contentVolumeSize }}