# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE

{{- /*
 nginx ingress needs path capture to achieve prefix type routing
*/}}
{{- $pathSuffix := "" }}
{{- if eq .Values.ingressType "nginx" }}
{{- $pathSuffix = "(.*)"}}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.idolingressName }}
  labels: {{- include "singlecontent.labels" . | nindent 4 }}
  annotations:
{{- if eq .Values.ingressType "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingressProxyBodySize }}
{{- else if eq .Values.ingressType "haproxy" }}
    haproxy.router.openshift.io/rewrite-target: / 
    haproxy.router.openshift.io/proxy-body-size: {{ .Values.ingressProxyBodySize }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ print "/content/" $pathSuffix }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.contentName }}
            port:
              name: {{ (index .Values.contentPorts 0).name }}
      - path: {{ print "/index/" $pathSuffix }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.contentName }}
            port: 
              name: {{ (index .Values.contentPorts 1).name }}
{{- if .Values.ingressHost }}
    host: {{ .Values.ingressHost }}
{{- end }}
