# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ include "idol-library.ingress" (dict 
    "root" .
    "component" .Values
    "ingress" .Values.ingress
    "destination" "single-content.ingress")  -}}
{{- define "single-content.ingress" -}}
{{/* Any View specific merges to base template go here */}}
{{- $root := get . "root" | required "missing root" -}}
{{- $component := get . "component" | required "missing component" -}}
spec:
  rules:
  - http:
      paths:
      - path: {{ include "idol-library.ingress.path" (dict "ingress" $component.ingress "path" $component.ingress.path) }}
        pathType: {{ include "idol-library.ingress.pathtype" $component }}
        backend:
          service:
            name:  {{ $component.name | quote }}
            port:
              name: aci-port
      - path: {{ include "idol-library.ingress.path" (dict "ingress" $component.ingress "path" $component.ingress.indexPath) }}
        pathType: {{ include "idol-library.ingress.pathtype" $component }}
        backend:
          service:
            name:  {{ $component.name | quote }}
            port:
              name: index-port
      - path: {{ include "idol-library.ingress.path" (dict "ingress" $component.ingress "path" $component.ingress.servicePath) }}
        pathType: {{ include "idol-library.ingress.pathtype" $component }}
        backend:
          service:
            name:  {{ $component.name | quote }}
            port:
              name: service-port
{{- end -}}
