# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-default-cfg
  labels: {{- include "idol-library.labels" . | nindent 4 }}
data:
  omnigroupserver.cfg: |
{{ tpl (.Files.Get "resources/omnigroupserver.cfg") . | indent 4 }}
{{- end -}}
{{- if .Values.oauthToolConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-oauth-startup-scripts
  labels: {{- include "idol-library.labels" . | nindent 4 }}
data:
  001_startup.sh: |
{{ tpl (.Files.Get "resources/001_oauth_startup.sh") . | nindent 4 }}
  utils/oauth_tool_setup.sh: |
{{ tpl (.Files.Get "resources/oauth_tool_setup.sh") . | nindent 4 }}
{{- end -}}