# BEGIN COPYRIGHT NOTICE
# Copyright 2023-2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- $env := list }}
{{- $volumes := list }}
{{- $volumeMounts := list }}
{{- if .Values.oauthToolConfigMap }}
{{- $env = append $env (dict "name" "OAUTH_TOOL_CFG" "value" "/etc/config/oauth/oauth_tool.cfg")}}
{{- $volumes = concat $volumes (list (dict "name" "oauth-tool-config-file" "configMap" (dict "name" .Values.oauthToolConfigMap)) (dict "name" "oauth-prestart-scripts" "configMap" (dict "name" (printf "%s-oauth-prestart-scripts-cm" .Values.name)))) }}
{{- $volumeMounts = concat $volumeMounts (list (dict "name" "oauth-tool-config-file" "mountPath" "/etc/config/oauth" "readOnly" true) (dict "name" "oauth-prestart-scripts" "mountPath" "/omnigroupserver/prestart_scripts" "readOnly" true)) }}
{{- end }}
{{ include "idol-library.aciserver.deployment" (dict 
    "root" .
    "component" .Values
    "env" $env
    "volumes" $volumes
    "volumeMounts" $volumeMounts
    "destination" "idol-omnigroupserver.deployment")  }}
{{- define "idol-omnigroupserver.deployment" -}}
{{/* Any OGS specific merges to base template go here */}}
{{- end -}}
