# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  labels: {{- include "idol-library.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name | quote }}
  template:
    metadata:
      labels: {{- include "idol-library.labels" . | nindent 8 }}
        app: {{ .Values.name | quote }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ .Values.name | quote }}
        image: {{ .Values.idolImageRegistry }}/{{ .Values.image }}:{{ .Values.idolVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /a=getpid
            port: aci-port
{{- template "idol-library.standardLivenessProbe" .Values.livenessProbe }}
        ports:
        - containerPort: {{ .Values.aciPort | int }}
          name: aci-port
          protocol: TCP
        - containerPort: {{ .Values.servicePort | int }}
          name: service-port
          protocol: TCP
        volumeMounts:
        - name: config-map
          mountPath: /etc/config/idol
  {{- if .Values.oauthToolConfigMap }}
        - name: oauth-tool-config-map
          mountPath: /etc/config/idol
        - name: oauth-startup-config-map
          mountPath: /omnigroupserver/prestart_scripts
  {{- end -}}
        env:
        - name: IDOL_COMPONENT_CFG
          value: "/etc/config/idol/omnigroupserver.cfg"
        - name: OAUTH_TOOL_CONFIG
          value: "/etc/config/idol/oauth_tool.cfg"
      volumes:
      - name: config-map
        configMap:
          name: {{ default (printf "%s-default-cfg" .Values.name) .Values.existingConfigMap }}
{{- if .Values.oauthToolConfigMap }}
      - name: oauth-tool-config-map
        configMap:
          name: {{ .Values.oauthToolConfigMap }}
      - name: oauth-startup-config-map
        configMap:
          name: {{ .Values.name }}-oauth-startup-scripts
{{- end -}}
