# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ include "idol-library.aciserver.deployment" (dict 
    "root" .
    "component" .Values
    "destination" "idol-omnigroupserver.deployment")  }}
{{- define "idol-omnigroupserver.deployment" -}}
{{/* Any OGS specific merges to base template go here */}}
{{- if .Values.oauthToolConfigMap }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.name | quote }}
        volumeMounts:
        - name: oauth-tool-config-map
          mountPath: /etc/config/idol
        - name: oauth-startup-config-map
          mountPath: /omnigroupserver/prestart_scripts
        env:
        - name: OAUTH_TOOL_CONFIG
          value: "/etc/config/idol/oauth_tool.cfg"
      volumes:
      - name: oauth-tool-config-map
        configMap:
          name: {{ .Values.oauthToolConfigMap }}
      - name: oauth-startup-config-map
        configMap:
          name: {{ .Values.name }}-oauth-startup-scripts
{{- end -}}
{{- end -}}
