# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: pxi-config
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values ) | nindent 4 }}
data:
  pii.cfg: |-
{{ tpl (print "resources/pii.cfg" | .Files.Get) . | indent 4 }}
  pii_telephone.cfg: |-
{{ tpl (print "resources/pii_telephone.cfg" | .Files.Get) . | indent 4 }}
  phi.cfg: |-
{{ tpl (print "resources/phi.cfg" | .Files.Get) . | indent 4 }}
  phi_internet.cfg: |-
{{ tpl (print "resources/phi_internet.cfg" | .Files.Get) . | indent 4 }}
  phi_telephone.cfg: |-
{{ tpl (print "resources/phi_telephone.cfg" | .Files.Get) . | indent 4 }}
  pci.cfg: |-
{{ tpl (print "resources/pci.cfg" | .Files.Get) . | indent 4 }}
  psi.cfg: |-
{{ tpl (print "resources/psi.cfg" | .Files.Get) . | indent 4 }}