# BEGIN COPYRIGHT NOTICE
# Copyright 2022-2025 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-licenseserver
version: 0.5.0
description: Creates an IDOL LicenseServer proxy service accessible to other elements of the cluster