###
# Copyright (c) 2019-2020 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
###

# Basic IDOL container setup
# Uses nifi to ingest and index data into content
# Uses find to make search results available
# Default admin user is created for find in the community service
#  - see community/run_community.sh for details

version: "3.7"

x-common-labels: &common-labels
  docker-compose/instance: ${INSTANCE:-basic-idol}

x-common-server: &common-server
# Change the IP to the address of an external IDOL LicenseServer instance
  extra_hosts:
  - idol-licenseserver:${LICENSESERVER_IP}
  labels:
    <<: *common-labels

# Any files dropped into this volume will be ingested and indexed
volumes:
  idol-ingest-volume:
    labels:
      <<: *common-labels

services:
  idol-content: 
    <<: *common-server
    image: ${IDOL_REGISTRY}/content:${IDOL_SERVER_VERSION}
  idol-agentstore:
    <<: *common-server
    image: ${IDOL_REGISTRY}/agentstore:${IDOL_SERVER_VERSION}
  idol-categorisation-agentstore:
    <<: *common-server
    image: ${IDOL_REGISTRY}/categorisation-agentstore:${IDOL_SERVER_VERSION}
  idol-community:
    <<: *common-server
    image: ${IDOL_REGISTRY}/community:${IDOL_SERVER_VERSION}
    depends_on:
      - idol-content
      - idol-agentstore
  idol-view:
    <<: *common-server
    image: ${IDOL_REGISTRY}/view:${IDOL_SERVER_VERSION}
    depends_on:
      - idol-agentstore
  idol-nifi:
    <<: *common-server
    image: ${IDOL_REGISTRY}/nifi-minimal:${IDOL_SERVER_VERSION} # choose nifi-minimal or nifi-full
    shm_size: 256m
    environment:
      - NIFI_WEB_PROXY_CONTEXT_PATH=/idol-nifi
      - NIFI_WEB_HTTP_PORT=8081
      - NIFI_SENSITIVE_PROPS_KEY=my_nifi_sensitive_props_key
      - IDOL_NIFI_FLOWFILE=/opt/nifi/scripts/flow-basic-idol.json
    volumes:
      - idol-ingest-volume:/idol-ingest
      - ./nifi/resources/import-flow.sh:/opt/nifi/scripts/import-flow.sh
      - ./nifi/resources/basic-idol-entrypoint.sh:/opt/nifi/scripts/basic-idol-entrypoint.sh
      - ./nifi/flow/basic.json:/opt/nifi/scripts/flow-basic-idol.json
    entrypoint:
      - sh
      - -c
      - "/opt/nifi/scripts/basic-idol-entrypoint.sh"
  idol-find:
    image: ${IDOL_REGISTRY}/find:${IDOL_SERVER_VERSION}
    labels:
      <<: *common-labels
    environment:
      - IDOL_UI_CFG=config_basic.json # this controls the configuration of Find
    depends_on:
      - idol-community
      - idol-view
  httpd-reverse-proxy:
    image: httpd:2.4
    labels:
      <<: *common-labels
    volumes:
      - ./httpd-reverse-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - idol-find
      - idol-nifi
    ports:
      - 8080:8080
