###
# Copyright (c) 2019-2020 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
###

# This is designed to be used atop of docker-compose.add-mmap.yml
# Therefore the incantation to use this is something like
# docker-compose -f docker-compose.yml -f docker-compose.ssl.yml 
#  -f docker-compose.add-mmap.yml 
#  -f docker-compose.add-mmap.ssl.yml up 

version: "3.7"

# bind mount holding certificates
x-ssl-volume: &ssl-volume
  type: bind
  source: ../ssl/intermediate
  target: /ssl

services:
  idol-nifi:
    volumes:
      - ./nifi/flow/with.mmap.ssl.xml:/opt/nifi/flow/this_flow.xml:ro # this controls which NiFi flow is used
  idol-mediaserver:
    env_file:
      - idol_ssl.env    
    volumes:
      - *ssl-volume
  idol-mmap-app:
    env_file:
      - idol_ssl.env
    environment:
      - IDOL_SSL_COMMON_NAME=mmap.microfocus.com
      - IDOL_SSL_SUBJ_ALT_NAME=*.microfocus.com
    volumes:
      - *ssl-volume
# N.B. mmap doesn't yet support an https playlistserver      
#  idol-mmap-playlistserver:
#    env_file:
#      - idol_ssl.env
#    volumes:
#      - *ssl-volume
