# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: idol-nifi-keys-env
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifi) | nindent 4 -}}
    app: nifi
data:
  KEYSTORE_PASSWORD: {{ .Values.nifi.keystorePassword | default (randAlphaNum 24) | quote }}
  NIFI_SENSITIVE_PROPS_KEY: {{ .Values.nifi.sensitivePropsKey | default (randAlphaNum 24) | quote }}
  TRUSTSTORE_PASSWORD: {{ .Values.nifi.truststorePassword | default (randAlphaNum 24) | quote }}
