# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- range $nifiClusterItem := .Values.nifiClusters }}
{{ $nifiCluster := merge $nifiClusterItem $.Values.nifi (dict "clusterId" $.Values.name) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nifiCluster.clusterId }}-keys-env
  labels: {{- include "idol-library.labels" (dict "root" $ "component" $nifiCluster) | nindent 4 -}}
    app: {{ $nifiCluster.clusterId }}
data:
  KEYSTORE_PASSWORD: {{ $nifiCluster.keystorePassword | default (randAlphaNum 24) | quote }}
  NIFI_SENSITIVE_PROPS_KEY: {{ $nifiCluster.sensitivePropsKey | default (randAlphaNum 24) | quote }}
  TRUSTSTORE_PASSWORD: {{ $nifiCluster.truststorePassword | default (randAlphaNum 24) | quote }}
{{- end }}
