{{- if .Values.nifi.autoScaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nifi
  labels: {{- include "idol-nifi.labels" . | nindent 4 -}}
    app.kubernetes.io/name: nifi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nifi
  minReplicas: {{ .Values.nifi.autoScaling.minReplicas | int }}
  maxReplicas: {{ .Values.nifi.autoScaling.maxReplicas | int }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
  metrics:
{{ with .Values.nifi.autoScaling.metrics }}
{{- toYaml . | trim | indent 4 }}
{{- end }}

{{- end }}