# BEGIN COPYRIGHT NOTICE
# Copyright 2022-2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

{{ define "idolnifi.statefulset.base" -}}
{{/* specific merges to statefulset specification */}}
{{- $root := get . "root" | required "idolnifi.statefulset.base: missing root" -}}
{{- $component := get . "component" | required "idolnifi.statefulset.base: missing component" -}}
metadata:
  labels:
    app: nifi
    name: nifi
spec:
  serviceName: nifi
  template:
    spec:
      terminationGracePeriodSeconds: 90
      automountServiceAccountToken: false
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      initContainers:
      - name: wait-for-zookeeper
        image: docker.io/busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
          until nc -vzw 1 zookeeper 2181 ; do
            echo "Waiting for zookeeper to start"
            sleep 3
          done
        envFrom:
        - configMapRef:
            name: idol-nifi-env
            optional: false
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
          limits:
            cpu: 20m
            memory: 10Mi
        {{- if $component.containerSecurityContext.enabled }}
        securityContext: {{- omit $component.containerSecurityContext "enabled" | toYaml | nindent 10 }}
          readOnlyRootFilesystem: true
        {{- end }}
      - name: ensure-conf
        image: {{ include "idol-library.idolImage" (dict "root" $root "idolImage" $component.idolImage) }}
        envFrom:
        - configMapRef:
            name: idol-nifi-env
            optional: false
        resources:
          requests:
            cpu: {{ $component.nifi.resources.requests.cpu }}
            memory: {{ printf "%dMi" ( $component.nifi.resources.requests.memoryMi | int) }}
          limits:
            cpu: {{ $component.nifi.resources.limits.cpu }}
            memory: {{ printf "%dMi" ( $component.nifi.resources.limits.memoryMi | int) }}
        {{- if $component.containerSecurityContext.enabled }}
        securityContext: {{- omit $component.containerSecurityContext "enabled" | toYaml | nindent 10 }}
          readOnlyRootFilesystem: true
        {{- end }}
        command:
        - sh
        - "-c"
        - |
          if [ -z "$(ls -A -- /mnt/store/nifi/conf)" ]; then
            echo Copying files into conf directory
            cp /opt/nifi/nifi-current/conf/* /mnt/store/nifi/conf/
          fi

        volumeMounts:
        - name: statedata
          mountPath: /mnt/store/nifi/conf
          subPath: conf
          readOnly: false
      {{- if $component.podSecurityContext.enabled }}
      securityContext: {{- omit $component.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: statedata
      labels: {{- include "idol-library.labels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $component.nifi.dataVolume.storageClass }}
      resources:
        requests:
          storage: {{ $component.nifi.dataVolume.volumeSize }}
{{- end -}}

{{- include "idol-library.util.merge" (dict
  "root" .
  "component" .Values
  "source" "idol-library.aciserver.statefulset.base.v1"
  "destination" "idolnifi.statefulset.base" 
  "containers" (list "idolnifi.container")
  "volumes" (list (dict "name" "data" "emptyDir" (dict "sizeLimit" "3Gi"))
                  (dict "name" "scripts" "configMap" (dict "name" "idol-nifi-scripts" "optional" false "defaultMode" 0755)))
  "addConfigMap" false
) -}}


