apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-scripts-cm
  labels: {{- include "idol-nifi.labels" . | nindent 4 -}}
    app: nifi
data:
  security.sh: |
{{ tpl (.Files.Get "resources/nifi-security.sh") . | indent 4 }}
  wait.sh: |
{{ tpl (.Files.Get "resources/nifi-wait.sh") . | indent 4 }}
  connect-registry.sh: |
{{ tpl (.Files.Get "resources/nifi-connect-registry.sh") . | indent 4 }}
  preStop.sh: |
{{ tpl (.Files.Get "resources/nifi-preStop.sh") . | indent 4 }}
  postStart.sh: |
{{ tpl (.Files.Get "resources/nifi-postStart.sh") . | indent 4 }}
  import-flow.sh: | 
{{ tpl (.Files.Get "resources/nifi-import-flow.sh") . | indent 4 }}
  flow-basic-idol.json: |
{{ tpl (.Files.Get "resources/flow-basic-idol.json") . | indent 4 }}