---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nifi-basic-auth
  labels: {{- include "idol-nifi.labels" . | nindent 4 }}
    app: nifi
  annotations:
    app.kubernetes.io/name: nifi
    app.kubernetes.io/part-of: nifi
data:
  auth: {{ .Values.ingressBasicAuthData | quote }}
