# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nifi-basic-auth
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifi) | nindent 4 -}}
    app: {{ $.Values.name }}
  annotations:
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/part-of: {{ $.Values.name }}
data:
  auth: {{ .Values.ingressBasicAuthData | quote }}
