# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ include "idol-library.ingress" (dict 
    "root" .
    "component" .Values.content
    "ingress" .Values.content.ingress
    "destination" "distributedidol.content.ingress")  -}}
{{- define "distributedidol.content.ingress" -}}
{{- $root := get . "root" | required "missing root" -}}
{{- $component := get . "component" | required "missing component" -}}
{{- $pathType := (include "idol-library.ingress.pathtype" $component) -}}
spec:
  rules:
  - http:
      paths:
      - path: {{ include "idol-library.ingress.path" (dict "ingress" $component.ingress "path" "/content/") }}
        pathType: {{ $pathType }}
        backend:  
          service:
            name: {{ $component.name }}
            port:
              name: aci-port
{{- range $i := untilStep 0 ( $component.ingress.exposedContents | int ) 1 }}
      - path: {{ include "idol-library.ingress.path" (dict "ingress" $component.ingress "path" (print "/content-" $i "/")) }}
        pathType: {{ $pathType }}
        backend:
          service:
            name: {{ $component.name }}-{{ $i }}
            port:
              name: aci-port
{{- end }}
{{- end -}}
