# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
#
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

{{ define "distributed.content.statefulset.base" }}
{{- $root := get . "root" | required "distributed.content.statefulset.base: missing root" -}}
{{- $component := get . "component" | required "distributed.content.statefulset.base: missing component" -}}
spec:
  replicas: {{ int $component.initialEngineCount }}
  template:
    spec:
      terminationGracePeriodSeconds: 300
  volumeClaimTemplates:
  - metadata:
      name: index
      labels: {{- include "idol-library.labels.volumeClaimTemplates" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $component.contentStorageClass }}
      resources:
        requests:
          storage: {{ $component.contentVolumeSize }}
{{- end }}

{{- $contentVolumes := list (dict
    "name" "content-scripts"
    "configMap" (dict "name" (print .Values.content.name "-scripts"))
)}}
{{- if .Values.setupMirrored }}
{{- $contentVolumes = append $contentVolumes (dict
   "name" "archive-share"
   "persistentVolumeClaim" (dict "claimName" "backup-archive-pvc")
) }}
{{- end }}


{{ include "idol-library.util.merge" (dict
  "root" .
  "component" .Values.content
  "source" "idol-library.aciserver.statefulset.base.v1"
  "destination" "distributed.content.statefulset.base"
  "containers" (list "didolcontent.container")
  "volumes" $contentVolumes
) }}
