# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-answerserver
version: "0.4.0"
appVersion: "24.1"
description: Adds IDOL AnswerServer
dependencies:
- name: idol-library
  version: "0.13.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  alias: "passageextractorAgentstore"
  condition: passageextractorAgentstore.enabled
  version: "0.10.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  alias: "answerbankAgentstore"
  condition: answerbankAgentstore.enabled
  version: "0.10.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  condition: single-content.enabled
  version: "0.10.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: postgresql
  condition: postgresql.enabled
  version: "13.2.3"
  repository: https://charts.bitnami.com/bitnami