# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: idol-mmap-postgres-init
  labels: {{- include "idol-library.labels" . | nindent 4 }}
data:
  {{- $ctx := . }}
  {{- range tuple "00-schema.sql" "partition-word-table.sql" "searchable-text.sql" "stored-procedures.sql" }}
  {{ . }}: |-
{{ tpl (. | print "resources/postgres/" | $ctx.Files.Get) $ctx | indent 4 }}
  {{- end }}
