---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-archive-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.contentVolumeSize }}
  volumeName: {{ .Values.backupArchiveVolumeName }}
  storageClassName: ""