{{- if .Values.setupMirrored }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-archive-pvc
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.contentVolumeSize }}
  storageClassName: {{ .Values.backupArchiveStorageClass }}
{{- end }}
