# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
{{- if .Values.httpProxy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-proxy-config
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
data:
  https_proxy: {{ .Values.httpProxy }}
{{- end }}

