# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
{{- if .Values.autoscaling.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.custommetrics.name }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.custommetrics.servicePort | int }}
    targetPort: {{ .Values.custommetrics.containerPort | int }}
  selector:
    app: {{ .Values.custommetrics.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics:system:auth-delegator
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ .Values.custommetrics.name }}
  namespace: {{ include "idol-library.namespace" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-metrics-auth-reader
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.custommetrics.name }}
  namespace: {{ include "idol-library.namespace" . | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
    app: {{ .Values.custommetrics.name }}
  name: {{ .Values.custommetrics.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.custommetrics.name }}
  template:
    metadata:
      labels: {{- include "distributedidol.labels" . | nindent 8 }}
        app: {{ .Values.custommetrics.name }}
      name: {{ .Values.custommetrics.name }}
    spec:
      serviceAccountName: {{ .Values.custommetrics.name }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ .Values.custommetrics.name }}
        image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.1
        args:
        - /adapter
        - --secure-port={{ .Values.custommetrics.containerPort | int }}
        - --cert-dir=/tmp/cert
        - --prometheus-url=http://{{ .Values.prometheus.name }}:9090/
        - --metrics-relist-interval=1m
        - --v=4
        - --config=/etc/adapter/config.yaml
        ports:
        - containerPort: {{ .Values.custommetrics.containerPort | int }}
        volumeMounts:
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: config
        configMap:
          name: adapter-config
      - name: tmp-vol
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-resource-reader
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.custommetrics.name }}
  namespace: {{ include "idol-library.namespace" . | quote }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.custommetrics.name }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  service:
    name: {{ .Values.custommetrics.name }}
    namespace: {{ include "idol-library.namespace" . | quote }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-server-resources
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__="dih_full_ratio"}'
      resources:
        template: <<.Resource>>
      name:
        matches: "dih_full_ratio"
        as: "dih_full_ratio"
      metricsQuery: dih_full_ratio
    - seriesQuery: '{__name__="full_ratio_latch"}'
      resources:
        template: <<.Resource>>
      name:
        matches: "full_ratio_latch"
        as: "full_ratio_latch"
      metricsQuery: full_ratio_latch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-resource-reader
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-controller-custom-metrics
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
{{- end }}