# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: v1
kind: Service
metadata:
  # Use this service for generic IDOL index port functionality
  # Could point to e.g. a DAH or Content instance
  name: {{ .Values.queryserviceName }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ (index .Values.dahPorts 0).service | int }}
    targetPort: {{ (index .Values.dahPorts 0).name }}
    name: {{ (index .Values.dahPorts 0).name }}
  - port: {{ (index .Values.dahPorts 1).service | int }}
    targetPort: {{ (index .Values.dahPorts 1).name }}
    name: {{ (index .Values.dahPorts 1).name }}
  selector:
    app: {{ .Values.dahDeployment }}
---
apiVersion: v1
kind: Service
metadata:
  # Use this service for DAH-specific functionality, e.g. enginemanagement
  # Could get away with just the ACI port for now, but keep the set in case
  name: {{ .Values.dahName }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ (index .Values.dahPorts 0).service | int }}
    targetPort: {{ (index .Values.dahPorts 0).name }}
    name: {{ (index .Values.dahPorts 0).name }}
  - port: {{ (index .Values.dahPorts 1).service | int }}
    targetPort: {{ (index .Values.dahPorts 1).name }}
    name: {{ (index .Values.dahPorts 1).name }}
  selector:
    app: {{ .Values.dahDeployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dahDeployment }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dahDeployment }}
  template:
    metadata:
      labels: {{- include "distributedidol.labels" . | nindent 8 }}
        app: {{ .Values.dahDeployment }}
    spec:
      initContainers:
      - name: edit-config
        # Use this version of busybox so nslookup output format is stable
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        env:
        - name: IDOL_CONTENT_SERVICE_PORT_ACI_PORT
          # This doesn't seem to be set by our headless service
          value: {{ (index .Values.contentPorts 0).container | quote }}
        command:
        - sh
        - "-c"
        - |
{{ tpl (.Files.Get "resources/dah_init.sh") . | indent 10 }}
        volumeMounts:
        - name: config-map
          mountPath: /mnt/config-map
        - name: config-volume
          mountPath: /mnt/config/idol
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ .Values.dahName }}
        image: {{ .Values.idolImageRegistry }}/{{ .Values.dahImage }}:{{ .Values.idolVersion }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "cd /dah && command cp -f /etc/config/idol/dah.cfg dah.cfg && ./run_idol.sh"]
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - "-c"
              - |
{{ tpl (.Files.Get "resources/dah_preStop.sh") . | indent 16 }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/idol
        env:
        - name: IDOL_COMPONENT_CFG
          # Override default in newer IDOL containers
          value: "/dah/dah.cfg"
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbePath }}
            port: {{ (index .Values.dahPorts 0).container | int }}
{{- template "distributedidol.deployment.standardLivenessProbe" }}
        ports:
        - containerPort: {{ (index .Values.dahPorts 0).container | int }}
          name: {{ (index .Values.dahPorts 0).name }}
          protocol: TCP
        - containerPort: {{ (index .Values.dahPorts 1).container | int }}
          name: {{ (index .Values.dahPorts 1).name }}
          protocol: TCP
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: config-map
        configMap:
          name: idol-config
          