apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.licenseServerName }}
spec:
  ports:
    - port: {{ .Values.licenseServerPort | int }}
      targetPort: {{ .Values.licenseServerPort | int }}
      name: aci-port
  # no selector, create endpoint manually
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.licenseServerName }}
subsets:
  - addresses:
      - ip: {{ .Values.licenseServerIp | quote }}
    ports:
      - port: {{ .Values.licenseServerPort | int }}
        name: aci-port