# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2022 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-nifi
version: 0.1.0
appVersion: "23.4.0"
description: A configurable IDOL NiFi setup
dependencies:
- name: idol-library
  version: "0.1.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: "0.1.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
