# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-nifi
version: 0.4.0
appVersion: "24.1.0"
description: A configurable IDOL NiFi setup
dependencies:
- name: idol-library
  version: "0.10.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: "0.3.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: metrics-server
  condition: nifi.autoScaling.enabled
  version: "3.8.2"
  repository: "https://kubernetes-sigs.github.io/metrics-server"
