# BEGIN COPYRIGHT NOTICE
# Copyright 2023-2025 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-nifi
version: 0.14.1
appVersion: "25.1"
description: A configurable IDOL NiFi setup
dependencies:
- name: idol-library
  version: ~0.15.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: ~0.4.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: metrics-server
  condition: metrics-server.enabled
  version: "3.8.2"
  repository: "https://artifactory.otxlab.net/artifactory/api/helm/kubernetes-sigs.github.io-metrics-server"
- name: prometheus
  condition: prometheus.enabled
  version: "25.0.0"
  repository: "https://artifactory.otxlab.net/artifactory/prometheus-community-remote"
- name: prometheus-adapter
  condition: prometheus-adapter.enabled
  version: "4.2.0"
  repository: "https://artifactory.otxlab.net/artifactory/api/helm/prometheus-community-remote"
- name: postgresql-ha
  alias: postgresql
  condition: postgresql.enabled
  version: "14.3.4"
  repository: https://artifactory.otxlab.net/artifactory/charts.bitnami.com/
