###
# Copyright (c) 2019-2020 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
###

apiVersion: v1
name: basic-idol #needs to be the same as the directory
version: 0.1.0 #chart version (can do rollbacks, I believe)
appVersion: 1.0 #optional
description: A configurable basic idol setup #optional (for when you do helm search)