# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ include "idol-library.ingress" (dict 
    "root" .
    "component" .Values
    "ingress" .Values.ingress
    "destination" "idol-eductionserver.ingress")  -}}
{{- define "idol-eductionserver.ingress" -}}
{{/* Any Eduction Server specific merges to base template go here */}}
{{- end -}}
