apiVersion: v1
entries:
  distributed-idol:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-23T16:18:24.494314283Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 9f283e4544d07bb2464b6502687e311cefd88059db50b66a97f79097fd1c2641
    name: distributed-idol
    urls:
    - release/distributed-idol-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-10-18T17:09:11.453157282+01:00"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: cc56a0f3f6504d1a9bc0f08d6770102c6715f8aa3e1b55fd6bc2a97fac3d347d
    name: distributed-idol
    urls:
    - release/distributed-idol-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-10-11T16:58:07.823990721+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 52276f85f8e0d95915e5c8054c9f2aa4c26ddb9e96faf6fe52d92ef598176e5b
    name: distributed-idol
    urls:
    - release/distributed-idol-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 23.3.0
    created: "2023-09-13T16:14:54.852460093+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 8b44c9a3fe583bf7a8586c1df91576825986f356159e6299a5f7126eec879847
    name: distributed-idol
    urls:
    - release/distributed-idol-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 23.3.0
    created: "2023-07-03T09:53:58.923999341+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: e61beb2af5a7bcf15eb3b4c637391528fa74b3d021f014469c1f32ad5950f12f
    name: distributed-idol
    urls:
    - release/distributed-idol-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 12.12.0
    created: "2023-02-08T16:10:51.409741034Z"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 752ffdb33e1b91f5eb5d305d1a803cb225627db37729d84ca143a6d4656ad1e5
    name: distributed-idol
    urls:
    - release/distributed-idol-0.2.0.tgz
    version: 0.2.0
  idol-answerserver:
  - apiVersion: v2
    appVersion: "24.1"
    created: "2024-01-23T16:18:24.495849922Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - alias: passageextractorSingleAgentstore
      condition: passageextractorSingleAgentstore.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - alias: answerbankSingleAgentstore
      condition: answerbankSingleAgentstore.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    description: Adds IDOL ANSWERSERVER
    digest: fa5956af05394bbb1e400cb6a0ea29b35e73714a6d9f47edca150942bbe08f07
    name: idol-answerserver
    urls:
    - release/idol-answerserver-0.1.0.tgz
    version: 0.1.0
  idol-community:
  - apiVersion: v2
    appVersion: "23.4"
    created: "2024-01-23T16:18:24.496919336Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    description: Adds IDOL Community
    digest: 53a638e0c7451592356950d1bab2fa8b968238366580ff164d90d60aeab51fdf
    name: idol-community
    urls:
    - release/idol-community-0.1.0.tgz
    version: 0.1.0
  idol-find:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-23T16:18:24.497643704Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds ``Find`` UI and supporting servers (Community, View)
    digest: 638396bb3c26c3dfa6b39d3211508d76383dd98069ee7447058e7346cbb8a49e
    name: idol-find
    urls:
    - release/idol-find-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-01T13:50:28.8839507Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds ``Find`` UI and supporting servers (Community, View)
    digest: 68b75c779d3a81616c6ca87ddf2319e571243f6aad49100b8ca71a42af7f5cf6
    name: idol-find
    urls:
    - release/idol-find-0.1.0.tgz
    version: 0.1.0
  idol-library:
  - apiVersion: v2
    created: "2024-01-23T16:18:24.497796861Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: ed5073c33bcf41487a283a05cc10ee69c402033d13bc834e6299bfeab12bd89f
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    created: "2023-12-08T12:36:47.031976173Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: e8b6085460b44f660c352ab81030d3877064cce9a1f6269a961d89f9a1a2d81f
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    created: "2023-12-01T17:07:50.254417344Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: 1dbab0348991ab5a97e6d8a1f4dd16d47e5472a04889a13ee14174126f1e7e55
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2023-11-01T13:50:28.8864502Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: d1c02d5375c2242406d506adb604df40bf7b4c6401ab37a33e7ab1155fe8f2be
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2023-10-18T17:09:11.453440593+01:00"
    description: An IDOL Helm library chart for Kubernetes
    digest: bfc46e2db8fe1d953b4ad798c8ae818b5548f578be8639558f93af1889e5093d
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.1.0.tgz
    version: 0.1.0
  idol-licenseserver:
  - apiVersion: v2
    created: "2024-01-23T16:18:24.497954885Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Creates an IDOL LicenseServer proxy service accessible to other elements
      of the cluster
    digest: 12049775855b6ad547fb7c7889e730d839edd2271ab2a29c7b91a25a34861186
    name: idol-licenseserver
    urls:
    - release/idol-licenseserver-0.1.0.tgz
    version: 0.1.0
  idol-nifi:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-23T16:18:24.500133723Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable IDOL NiFi setup
    digest: 6a084e91d4c8379c34a2bf33e62ea5b882348dc3a9fd23a510d588863e8c6f29
    name: idol-nifi
    urls:
    - release/idol-nifi-0.1.0.tgz
    version: 0.1.0
  idol-omnigroupserver:
  - apiVersion: v2
    appVersion: "23.4"
    created: "2024-01-23T16:18:24.501006136Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds IDOL OmniGroupServer
    digest: 9c64e48b848e2d84727217b6023eeea64c5cf92008931ba5f5f9a7d726af72ac
    name: idol-omnigroupserver
    urls:
    - release/idol-omnigroupserver-0.1.0.tgz
    version: 0.1.0
  idol-qms:
  - apiVersion: v2
    appVersion: "24.1"
    created: "2024-01-23T16:18:24.503000791Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - alias: singleAgentstore
      condition: singleAgentstore.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    description: Adds IDOL QMS
    digest: 09c6a321b22cefe37be797350315a79dd9546bffa96a7eab3fd1ea3fe8b334d6
    name: idol-qms
    urls:
    - release/idol-qms-0.1.0.tgz
    version: 0.1.0
  idol-stack:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-23T16:18:24.517823457Z"
    dependencies:
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: distributed-idol.enabled
      name: distributed-idol
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.6.0
    - condition: idol-find.enabled
      name: idol-find
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-nifi.enabled
      name: idol-nifi
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: An IDOL setup
    digest: fb81e1ab2bc131e1b9f21ca1032495573ab3189dec90e68a23f8e7d3f6660ec9
    name: idol-stack
    urls:
    - release/idol-stack-0.1.0.tgz
    version: 0.1.0
  single-content:
  - apiVersion: v2
    appVersion: "24.1"
    created: "2024-01-23T16:18:24.518499886Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 06f78fc9748d96cf92ea550f584cdd8d3bb020bbddafcff9920bdce55c46bfd8
    name: single-content
    urls:
    - release/single-content-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-12-11T13:56:42.874878178Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: fbc374c8351405d7827858d202448763ee4d444e20436e525f8269e0e2a2e9dc
    name: single-content
    urls:
    - release/single-content-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-03T11:06:41.6263262Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 15e7e37ac09433b348d9554bc7e9b30a62759142a1aad0c75eec52a541f3a1b0
    name: single-content
    urls:
    - release/single-content-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-01T13:50:28.8890166Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 94c8af7d24706c99f2d1a944b18c85c4fbf49125bc3c11a6cc46ef7c9746cb01
    name: single-content
    urls:
    - release/single-content-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-23T16:18:24.492023783Z"
