# BEGIN COPYRIGHT NOTICE
# (c) Copyright 2023 Micro Focus or one of its affiliates.
# END COPYRIGHT NOTICE
apiVersion: v1
entries:
  distributed-idol:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.598333299Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: b64aab0f7d3536b37108844135a1bb313e68b54aeee2c5d788ad268ed3f538c2
    name: distributed-idol
    urls:
    - release/distributed-idol-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-10-18T17:09:11.453157282+01:00"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: cc56a0f3f6504d1a9bc0f08d6770102c6715f8aa3e1b55fd6bc2a97fac3d347d
    name: distributed-idol
    urls:
    - release/distributed-idol-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-10-11T16:58:07.823990721+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 52276f85f8e0d95915e5c8054c9f2aa4c26ddb9e96faf6fe52d92ef598176e5b
    name: distributed-idol
    urls:
    - release/distributed-idol-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 23.3.0
    created: "2023-09-13T16:14:54.852460093+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 8b44c9a3fe583bf7a8586c1df91576825986f356159e6299a5f7126eec879847
    name: distributed-idol
    urls:
    - release/distributed-idol-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 23.3.0
    created: "2023-07-03T09:53:58.923999341+01:00"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: e61beb2af5a7bcf15eb3b4c637391528fa74b3d021f014469c1f32ad5950f12f
    name: distributed-idol
    urls:
    - release/distributed-idol-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 12.12.0
    created: "2023-02-08T16:10:51.409741034Z"
    dependencies:
    - condition: setupMirrored
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: A configurable distributed IDOL setup
    digest: 752ffdb33e1b91f5eb5d305d1a803cb225627db37729d84ca143a6d4656ad1e5
    name: distributed-idol
    urls:
    - release/distributed-idol-0.2.0.tgz
    version: 0.2.0
  idol-community:
  - apiVersion: v2
    appVersion: "23.4"
    created: "2024-01-15T16:18:50.605911226Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    description: Adds IDOL Community
    digest: 61067418b11f34c7af71085b3f7783908cfdc26c9d387397f1e8fe323225e074
    name: idol-community
    urls:
    - release/idol-community-0.1.0.tgz
    version: 0.1.0
  idol-find:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.613557154Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds ``Find`` UI and supporting servers (Community, View)
    digest: d1e3b18c89967542844fc988614f195e90528cde25216fd9a76bd2339f6681c1
    name: idol-find
    urls:
    - release/idol-find-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-01T13:50:28.8839507Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds ``Find`` UI and supporting servers (Community, View)
    digest: 68b75c779d3a81616c6ca87ddf2319e571243f6aad49100b8ca71a42af7f5cf6
    name: idol-find
    urls:
    - release/idol-find-0.1.0.tgz
    version: 0.1.0
  idol-library:
  - apiVersion: v2
    created: "2024-01-15T16:18:50.619761676Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: bf529b66622b9799d0eb7ecdd06a673dc1ec216d445b99393bd69eb40d329745
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    created: "2023-12-08T12:36:47.031976173Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: e8b6085460b44f660c352ab81030d3877064cce9a1f6269a961d89f9a1a2d81f
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    created: "2023-12-01T17:07:50.254417344Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: 1dbab0348991ab5a97e6d8a1f4dd16d47e5472a04889a13ee14174126f1e7e55
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2023-11-01T13:50:28.8864502Z"
    description: An IDOL Helm library chart for Kubernetes
    digest: d1c02d5375c2242406d506adb604df40bf7b4c6401ab37a33e7ab1155fe8f2be
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2023-10-18T17:09:11.453440593+01:00"
    description: An IDOL Helm library chart for Kubernetes
    digest: bfc46e2db8fe1d953b4ad798c8ae818b5548f578be8639558f93af1889e5093d
    name: idol-library
    type: library
    urls:
    - release/idol-library-0.1.0.tgz
    version: 0.1.0
  idol-licenseserver:
  - apiVersion: v2
    created: "2024-01-15T16:18:50.625673898Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Creates an IDOL LicenseServer proxy service accessible to other elements
      of the cluster
    digest: afcc8e8ab45e71142c6a6b7b369380a721ce83f81264a28c6ee768894c330ce5
    name: idol-licenseserver
    urls:
    - release/idol-licenseserver-0.1.0.tgz
    version: 0.1.0
  idol-nifi:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.634385529Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable IDOL NiFi setup
    digest: ed634b779a14146fa413f558cc49ec39a5ad7f69bd98194f046a8b244f7bc3a7
    name: idol-nifi
    urls:
    - release/idol-nifi-0.1.0.tgz
    version: 0.1.0
  idol-omnigroupserver:
  - apiVersion: v2
    appVersion: "23.4"
    created: "2024-01-15T16:18:50.640995753Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: Adds IDOL OmniGroupServer
    digest: 9e7fa07ae6b7de780a1ee3078c48714983ffe357928c8d5edfbe904276e23baf
    name: idol-omnigroupserver
    urls:
    - release/idol-omnigroupserver-0.1.0.tgz
    version: 0.1.0
  idol-qms:
  - apiVersion: v2
    appVersion: "23.4"
    created: "2024-01-15T16:18:50.650149486Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - alias: single-agentstore
      condition: single-agentstore.enabled
      name: single-content
      repository: file://../single-content
      version: 0.4.0
    - condition: single-content.enabled
      name: single-content
      repository: file://../single-content
      version: 0.4.0
    description: Adds IDOL QMS
    digest: d9fd4eca458236f6b60772d37104cdb21392de7a4750b3dd2c8b3f9b74bd3bef
    name: idol-qms
    urls:
    - release/idol-qms-0.1.0.tgz
    version: 0.1.0
  idol-stack:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.66256923Z"
    dependencies:
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: single-content.enabled
      name: single-content
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: distributed-idol.enabled
      name: distributed-idol
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.6.0
    - condition: idol-find.enabled
      name: idol-find
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.2.0
    - condition: idol-nifi.enabled
      name: idol-nifi
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: An IDOL setup
    digest: 5bb9408fc2f38ae30d637884bf002b31b0e88e0ef16c9b1f1bd585de26bedc5b
    name: idol-stack
    urls:
    - release/idol-stack-0.1.0.tgz
    version: 0.1.0
  single-content:
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.676155079Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 345e80a9e9f2a8bd206cfaeeb046d27c85300ddc977efa6b51d0a389972da702
    name: single-content
    urls:
    - release/single-content-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2024-01-15T16:18:50.669194754Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.4.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: d9f0d06c7932cca369ad1e7744becee391b51434af75834b53803018a587c51d
    name: single-content
    urls:
    - release/single-content-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-03T11:06:41.6263262Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 15e7e37ac09433b348d9554bc7e9b30a62759142a1aad0c75eec52a541f3a1b0
    name: single-content
    urls:
    - release/single-content-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 23.4.0
    created: "2023-11-01T13:50:28.8890166Z"
    dependencies:
    - name: idol-library
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    - condition: idol-licenseserver.enabled
      name: idol-licenseserver
      repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
      version: 0.1.0
    description: A configurable single-IDOL setup
    digest: 94c8af7d24706c99f2d1a944b18c85c4fbf49125bc3c11a6cc46ef7c9746cb01
    name: single-content
    urls:
    - release/single-content-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-15T16:18:50.588621164Z"
