# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

apiVersion: v2
name: idol-stack
version: 0.2.0
appVersion: "24.1.0"
description: An IDOL setup
dependencies:
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: "0.4.0"
  repository: file://../idol-licenseserver
- name: single-content
  condition: single-content.enabled
  version: "0.10.0"
  repository: file://../single-content
- name: distributed-idol
  condition: distributed-idol.enabled
  version: "0.10.0"
  repository: file://../distributed-idol
- name: idol-nifi
  condition: idol-nifi.enabled
  version: "0.8.0"
  repository: file://../idol-nifi
