# BEGIN COPYRIGHT NOTICE
# Copyright 2024-2025 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-qms
version: "0.7.3"
appVersion: "25.1"
description: Adds Knowledge Discovery QMS
dependencies:
- name: idol-library
  version: ~0.15.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  alias: "singleAgentstore"
  condition: singleAgentstore.enabled
  version: ~0.11.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  condition: single-content.enabled
  version: ~0.11.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
