# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

{{- if .Values.singleAgentstore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: idol-qms-agentstore-cfg
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.singleAgentstore ) | nindent 4 }}

data:
  qms-agentstore.cfg: |
{{ tpl (print "resources/qms-agentstore.cfg" | .Files.Get) . | indent 4 }}

  qms-agentstore-poststart.sh: |
{{ tpl (print "resources/qms-agentstore-poststart.sh" | .Files.Get) . | indent 4 }}
{{- end }}