# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dah.name }}-scripts
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
data:
{{- range $i, $val := list "common_utils.sh" "dah_init.sh" "dah_preStop.sh"}}
  {{ print $val }}: |
{{ tpl ($.Files.Get (print "resources/" $val)) $ | indent 4 }}
{{ end -}}
