# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ $component := .Values.dah }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component.name }}
  labels: {{- include "distributedidol.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $component.name }}
  template:
    metadata:
      labels: {{- include "distributedidol.labels" . | nindent 8 }}
        app: {{ $component.name }}
    spec:
      initContainers:
      - name: edit-config
        # Use this version of busybox so nslookup output format is stable
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        env:
        - name: IDOL_CONTENT_SERVICE_PORT_ACI_PORT
          # This doesn't seem to be set by our headless service
          value: {{ .Values.content.aciPort | quote }}
        {{- if $component.envConfigMap }}
        envFrom:
        - configMapRef: {{ $component.envConfigMap | quote }}
        {{ end }}
        command:
        - sh
        - "-c"
        - |
{{ tpl (.Files.Get "resources/dah_init.sh") . | indent 10 }}
        volumeMounts:
        - name: config-map
          mountPath: /mnt/config-map
        - name: config-volume
          mountPath: /mnt/config/idol
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: {{ $component.name }}
        image: {{ include "idol-library.idolImage" (dict "root" . "idolImage" $component.idolImage )}}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "cd /dah && command cp -f /etc/config/idol/dah.cfg dah.cfg && ./run_idol.sh"]
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - "-c"
              - |
{{ tpl (.Files.Get "resources/dah_preStop.sh") . | indent 16 }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/idol
        {{- range $component.additionalVolumeMounts }}
        - {{ . | toYaml | nindent 10 }}
        {{- end }}
        env:
        - name: IDOL_COMPONENT_CFG
          # Override default in newer IDOL containers
          value: "/dah/dah.cfg"
        livenessProbe:
          httpGet:
            path: /a=getpid
            port: {{ $component.aciPort | int }}
{{- template "idol-library.standardLivenessProbe" $component.livenessProbe }}
        ports:
        - containerPort: {{ $component.aciPort | int }}
          name: aci-port
          protocol: TCP
        - containerPort: {{ $component.servicePort | int }}
          name: service-port
          protocol: TCP
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: config-map
        configMap:
          name: {{ default (printf "%s-default-cfg" $component.name) $component.existingConfigMap }}
      {{- range $component.additionalVolumes }}
      - {{ . | toYaml | nindent 8 }}
      {{- end }}
          