# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ $component := .Values.dah }}

{{ define "distributedidol.dah.deployment.base" }}
{{- $root := get . "root" | required "distributedidol.dah.deployment.base: missing root" -}}
{{- $component := get . "component" | required "distributedidol.dah.deployment.base: missing component" -}}
spec:
  template:
    spec:
      initContainers:
      - name: edit-config
        # Use this version of busybox so nslookup output format is stable
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        env:
        - name: IDOL_CONTENT_SERVICE_PORT_ACI_PORT
          # This doesn't seem to be set by our headless service
          value: {{ $root.Values.content.aciPort | quote }}
        {{- if $component.envConfigMap }}
        envFrom:
        - configMapRef: {{ $component.envConfigMap | quote }}
        {{ end }}
        command:
        - sh
        - "-c"
        - |
{{ tpl ($root.Files.Get "resources/dah_init.sh") $root | indent 10 }}
        volumeMounts:
        - name: config-map
          mountPath: /mnt/config-map
        - name: config-volume
          mountPath: /mnt/config/idol
{{- end -}}

{{- $dahValues := merge .Values.dah (dict "global" .Values.global) }}

{{ include "idol-library.util.merge" (dict
  "root" .
  "component" $dahValues
  "source" "idol-library.aciserver.deployment.base.v1"
  "destination" "distributedidol.dah.deployment.base"
  "containers" (list "distributedidol.dah.container")
  "volumes" (list (dict "name" "config-volume" "emptyDir" (dict)))
) }}