# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

# Use this service for DAH-specific functionality, e.g. enginemanagement
# Could get away with just the ACI port for now, but keep the set in case
{{ include "idol-library.aciserver.service" (dict 
    "root" .
    "component" .Values.dah
    "destination" "distributedidol.dah.service") }}
{{- define "distributedidol.dah.service" -}}
{{/* Any DAH specific merges to base template go here */}}
{{- end -}}