# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- if and .Values.nifi.autoScaling.enabled .Values.nifiMetrics.enabled .Values.nifiPrometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: idol-nifi-metrics
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: idol-nifi-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics:system:auth-delegator
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: idol-nifi-metrics
  namespace: {{ include "idol-library.namespace" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-metrics-auth-reader
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: idol-nifi-metrics
  namespace: {{ include "idol-library.namespace" . | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
    app: idol-nifi-metrics
  name: idol-nifi-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idol-nifi-metrics
  template:
    metadata:
      labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 8 }}
        app: idol-nifi-metrics
      name: idol-nifi-metrics
    spec:
      serviceAccountName: idol-nifi-metrics
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
      - name: idol-nifi-metrics
        image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.1
        args:
        - /adapter
        - --secure-port=6443
        - --cert-dir=/tmp/cert
        - --prometheus-url=http://nifi-prometheus:9090/prometheus
        - --metrics-relist-interval=1m
        - --v=4
        - --config=/etc/adapter/config.yaml
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: config
        configMap:
          name: adapter-config
      - name: tmp-vol
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-resource-reader
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: idol-nifi-metrics
  namespace: {{ include "idol-library.namespace" . | quote }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: idol-nifi-metrics
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
spec:
  service:
    name: idol-nifi-metrics
    namespace: {{ include "idol-library.namespace" . | quote }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-server-resources
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__="nifi_amount_items_queued"}'
      resources:
        overrides:
          kubernetes_pod_name:
            resource: pod
          kubernetes_namespace:
            resource: namespace
      name:
        matches: ".*"
        as: "nifi_amount_items_queued_total"
      metricsQuery: 'nifi_amount_items_queued{component_type="RootProcessGroup"}'
    - seriesQuery: '{__name__="nifi_amount_items_queued"}'
      resources:
        overrides:
          kubernetes_pod_name:
            resource: pod
          kubernetes_namespace:
            resource: namespace
      name:
        matches: ".*"
        as: "nifi_amount_items_queued_avg"
      metricsQuery: 'avg(nifi_amount_items_queued{component_type="Connection"}) by (kubernetes_pod_name,kubernetes_namespace)'
    - seriesQuery: '{__name__="nifi_percent_used_count"}'
      resources:
        overrides:
          kubernetes_pod_name:
            resource: pod
          kubernetes_namespace:
            resource: namespace
      name:
        matches: ".*"
        as: "nifi_percent_used_count_max"
      metricsQuery: 'max(nifi_percent_used_count{component_type="Connection"}) by (kubernetes_pod_name,kubernetes_namespace)'
    - seriesQuery: '{__name__="nifi_percent_used_count"}'
      resources:
        overrides:
          kubernetes_pod_name:
            resource: pod
          kubernetes_namespace:
            resource: namespace
      name:
        matches: ".*"
        as: "nifi_percent_used_count_avg"
      metricsQuery: 'avg(nifi_percent_used_count{component_type="Connection"}) by (kubernetes_pod_name,kubernetes_namespace) or vector(0)'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-resource-reader
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-controller-custom-metrics
  labels: {{- include "idol-library.labels" (dict "root" . "component" .Values.nifiMetrics) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
{{- end }}