# BEGIN COPYRIGHT NOTICE
# Copyright 2023-2024 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

# As per https://helm.sh/docs/topics/charts/#the-chart-file-structure
# this values.yaml file contains the default configuration values for this chart.
# These default values can be overridden by using the --values or --set flags on the `helm install`
# command: see https://helm.sh/docs/helm/helm_install/

global:
  # --Global override value for idolImage.registry
  idolImageRegistry: ""
  # -- Global override value for idolImage.version
  idolVersion: ""
  # -- Global secrets used to pull container images
  imagePullSecrets:
  - "dockerhub-secret"


idolImage:
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  registry: "microfocusidolserver"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  version: "24.1"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  repo: "omnigroupserver"

# -- whether aci/service/index ports are configured to use TLS (https).
# If configuring for TLS, then consider setting IDOL_SSL_COMPONENT_CERT_PATH and IDOL_SSL_COMPONENT_KEY_PATH in envConfigMap
# to provide required TLS certificates
usingTLS: false

# existingConfigMap -- if specified, mounted at /etc/config/idol and expected to provide omnigroupserver.cfg
existingConfigMap: ""

# oauthToolConfigMap -- if specified, is the name of a ConfigMap that is expected to provide oauth_tool.cfg.
# It will be mounted at /etc/config/oauth and used by oauth_tool.exe to generate necessary OAuth configuration.
# Be aware that this WILL NOT WORK if the OAuth workflow requires user interaction. If this is the case, the
# OAuth workflow must be conducted elsewhere and the resulting files mounted into the Omnigroupserver
# container at the expected places for your configuration.
oauthToolConfigMap: ""

# -- Additional PodSpec Volume (see https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes)
additionalVolumes: []

# -- Additional PodSpec VolumeMount (see https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1)
additionalVolumeMounts: []

# -- Optional configMap name holding extra environnment variables for container
envConfigMap: ""

# -- Optional PodSecurityContext (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podsecuritycontext-v1-core)
podSecurityContext:
  # -- enable PodSecurityContext. Setting to false omits.
  enabled: false
  fsGroup: 0
  runAsUser: 1000
  runAsGroup: 0

# -- Optional SecurityContext for container (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#securitycontext-v1-core)
containerSecurityContext:
  # -- enable SecurityContext for container. Setting to false omits.
  enabled: false

##### INGRESS VARIABLES #####

ingress:
  # -- Create ingress resource
  enabled: true

  # -- Ingress controller type to setup for.
  # Valid values are nginx or haproxy (used by OpenShift)
  type: nginx

  # -- Optional parameter to override the default ingress class
  className: ""

  # -- Optional host (see https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules).
  # For an OpenShift environment this is required (see https://docs.openshift.com/container-platform/4.11/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)
  host: ""

##### INTERNAL VARIABLES #####
# Values specified below this point in the file should not need to be overriden.
# They are generally here in values.yaml so that DRY principles and a consistent
# scheme for specifying these values in the templates can be followed.

# licenseServerHostname -- the hostname of the IDOL LicenseServer (or abstraction)
licenseServerHostname: "idol-licenseserver"
# licenseServerPort -- the ACI port of the IDOL LicenseServer (or abstraction)
licenseServerPort: "20000"

# name -- used to name deployment, service, ingress
name: "idol-omnigroupserver"
# aciPort -- port service will serve ACI connections on
aciPort: "3057"
# servicePort -- port service will serve service connections on
servicePort: "3058"
# livenessProbe -- container livenessProbe settings
livenessProbe:
  initialDelaySeconds: 30

##### SUB-CHART VARIABLES #####
idol-licenseserver:
  # -- whether to deploy the idol-licenseserver sub-chart
  enabled: false