# BEGIN COPYRIGHT NOTICE
# Copyright 2023-2025 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

# As per https://helm.sh/docs/topics/charts/#the-chart-file-structure
# this values.yaml file contains the default configuration values for this chart.
# These default values can be overridden by using the --values or --set flags on the `helm install`
# command: see https://helm.sh/docs/helm/helm_install/

global:
  # -- Global override value for idolImage.registry
  # @section -- Globals
  idolImageRegistry: ""
  # -- Global override value for idolImage.version
  # @section -- Globals
  idolVersion: ""
  # -- Global secrets used to pull container images
  # @section -- Globals
  imagePullSecrets:
  - "dockerhub-secret"
  # -- Global override value for idolImage.imagePullPolicy, has no effect if it is empty or is removed
  # @section -- Globals
  imagePullPolicy: ""
  # -- Optional Secret containing OEM licensekey.dat and versionkey.dat files for licensing
  # @section -- Globals
  idolOemLicenseSecret: ""

idolImage:
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  registry: "microfocusidolserver"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  version: "25.1"
  # -- used to construct container image name: {idolImage.registry}/{idolImage.repo}:{idolImage.version}
  repo: "omnigroupserver"
  # -- used to determine whether to pull the specified image (see https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)
  imagePullPolicy: "IfNotPresent"

# -- Additional annotations applied to deployment/statefulset (https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)
annotations: {}

# -- Additional labels applied to all objects (https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)
labels: {}

# ogsVolumeSize -- Size of the PersistentVolumeClaim that is created
# for each OmniGroupServer instance. The Kubernetes cluster will need to provide
# enough PersistentVolumes to satisify the claims made for the desired number
# of OmniGroupServer instances.
ogsVolumeSize: 2Gi

# ogsStorageClass -- Name of the storage class used to provision a PersistentVolume
# for each OmniGroupServer instance.
# The associated PVCs are named index-{name}-{pod number}
ogsStorageClass: "idol-ogs-storage-class"

# -- whether aci/service/index ports are configured to use TLS (https).
# If configuring for TLS, then consider setting IDOL_SSL_COMPONENT_CERT_PATH and IDOL_SSL_COMPONENT_KEY_PATH in envConfigMap
# to provide required TLS certificates
usingTLS: false

# -- if specified, mounted at /etc/config/idol and expected to provide omnigroupserver.cfg
existingConfigMap: ""

# oauthToolConfigMap -- if specified, is the name of a ConfigMap that is expected to provide oauth_tool.cfg.
# It will be mounted at /etc/config/oauth and used by oauth_tool.exe to generate necessary OAuth configuration.
# Be aware that this WILL NOT WORK if the OAuth workflow requires user interaction. If this is the case, the
# OAuth workflow must be conducted elsewhere and the resulting files mounted into the Omnigroupserver
# container at the expected places for your configuration.
oauthToolConfigMap: ""

# -- Additional PodSpec Volume(s) (see <https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes>)
# Can be dict of (name, Volume), or list of (Volume). dict form allows for merging definitions from multiple values files.
additionalVolumes: null

# -- Additional PodSpec VolumeMount(s) (see <https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1>)
# Can be dict of (name, VolumeMount), or list of (VolumeMount). dict form allows for merging definitions from multiple values files.
additionalVolumeMounts: null

# -- Optional configMap name holding extra environnment variables for container
envConfigMap: ""

# -- Optional PodSecurityContext (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podsecuritycontext-v1-core)
podSecurityContext:
  # -- enable PodSecurityContext. Setting to false omits.
  enabled: false
  fsGroup: 0
  runAsUser: 1000
  runAsGroup: 0

# -- Optional SecurityContext for container (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#securitycontext-v1-core)
containerSecurityContext:
  # -- enable SecurityContext for container. Setting to false omits.
  enabled: false
  privileged: false
  runAsNonRoot: true

# -- Optional resources for container (see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers)
resources:
  # -- enable resources for container. Setting to false omits.
  enabled: false
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# -- Optional serviceAccountName for the pods (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account)
serviceAccountName: ""

##### INGRESS VARIABLES #####

ingress:
  # -- Create ingress resource
  # @section -- Ingress
  enabled: true

  # -- Ingress controller type to setup for.
  # Valid values are nginx or haproxy (used by OpenShift)
  # @section -- Ingress
  type: nginx

  # -- Optional parameter to override the default ingress class
  # @section -- Ingress
  className: ""

  # -- Optional host (see https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules).
  # For an OpenShift environment this is required (see https://docs.openshift.com/container-platform/4.11/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)
  # @section -- Ingress
  host: ""

  # -- Ingress controller path for ACI connections.
  # @section -- Ingress
  path: "/omnigroupserver/"

  # -- Ingress controller path for service connections.  Empty string to disable.
  # @section -- Ingress
  servicePath: "/omnigroupserver/service/"

  # -- Maximum allowed size of the client request body, defining
  # the maximum size of requests that can be made to IDOL components within the installation, e.g.
  # the amount of data sent in DREADDDATA index commands.
  # The value should be an nginx "size" value.
  # See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size for the documentation of the
  # corresponding nginx configuration parameter.
  # @section -- Ingress
  proxyBodySize: 2048m

  # -- Ingress controller specific annotations
  # Some annotations are added automatically based on ingress.type and other values, but can 
  # be overridden/augmented here
  # e.g. https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations
  # @section -- Ingress
  annotations: {}

  # -- Whether ingress uses TLS. You must set an ingress host to use this. 
  # See https://kubernetes.io/docs/concepts/services-networking/ingress/#tls 
  # @section -- Ingress
  tls:
    # -- The name of the secret for ingress TLS. Leave empty if not using TLS. 
    # If specified then either this secret must already exist, or crt and key values must be provided and secret will be created.. 
    # @section -- Ingress
    secretName: ""

    # -- Certificate data value to generate tls Secret (should be base64 encoded)
    # @section -- Ingress
    crt: ""

    # -- Private key data value to generate tls Secret (should be base64 encoded)
    # @section -- Ingress
    key: ""

##### INTERNAL VARIABLES #####
# Values specified below this point in the file should not need to be overriden.
# They are generally here in values.yaml so that DRY principles and a consistent
# scheme for specifying these values in the templates can be followed.

# licenseServerHostname -- the hostname of the IDOL LicenseServer (or abstraction)
licenseServerHostname: "idol-licenseserver"
# licenseServerPort -- the ACI port of the IDOL LicenseServer (or abstraction)
licenseServerPort: "20000"

# name -- used to name deployment, service, ingress
name: "idol-omnigroupserver"

# -- Expected working directory for the container.
# Should only need to change this for a heavily customized image.
workingDir: "/omnigroupserver"

# aciPort -- port service will serve ACI connections on
aciPort: "3057"
# servicePort -- port service will serve service connections on
servicePort: "3058"
# livenessProbe -- container livenessProbe settings
livenessProbe:
  initialDelaySeconds: 30

##### SUB-CHART VARIABLES #####
idol-licenseserver:
  # -- whether to deploy the idol-licenseserver sub-chart
  enabled: false